name: flutter_app_workspace
environment:
  sdk: ^3.8.1

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^7.4.1

workspace:
  - apps/finance_app
  - packages/core
  - packages/design_system
  - packages/home_screen
  - packages/history_screen
  - packages/budgets_screen
  - packages/voice_android
  - packages/voice_ios
  - packages/voice_platform_interface
  - packages/voice_plugin
  - packages/voice_recognition_feature
  - packages/transaction_feature

melos:
  name: finance
  useRootAsPackage: true
  sdkPath: .fvm/flutter_sdk

  packages:
    - apps/*
    - packages/*

  command:
    bootstrap:
      runPubGetInParallel: false

  scripts:
    analyze:
      run: melos exec -- flutter analyze

    test:
      run: melos exec -- flutter test

    pub_get:
      run: melos exec -- flutter pub get

    format:
      run: melos exec -- dart format .

    build_runner:
      run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

    clean:
      run: melos exec -- flutter clean
